import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import {
  brandConfig,
  type BrandColorToken,
} from '../src/shared/config/brand-config';

const outputPath = path.resolve('src/global.css');

const cssNames: Record<BrandColorToken, string> = {
  background: 'background',
  foreground: 'foreground',
  surface: 'surface',
  surfaceMuted: 'surface-muted',
  card: 'card',
  cardForeground: 'card-foreground',
  primary: 'primary',
  primaryForeground: 'primary-foreground',
  secondary: 'secondary',
  secondaryForeground: 'secondary-foreground',
  muted: 'muted',
  mutedForeground: 'muted-foreground',
  accent: 'accent',
  accentForeground: 'accent-foreground',
  success: 'success',
  successForeground: 'success-foreground',
  warning: 'warning',
  warningForeground: 'warning-foreground',
  destructive: 'destructive',
  destructiveForeground: 'destructive-foreground',
  border: 'border',
  input: 'input',
  ring: 'ring',
};

function hexToRgbTriplet(value: string) {
  const normalized = value.replace('#', '');

  if (!/^[0-9a-f]{6}$/i.test(normalized)) {
    throw new Error(`Theme color must be a six-digit hex value: ${value}`);
  }

  return [0, 2, 4]
    .map((index) =>
      Number.parseInt(normalized.slice(index, index + 2), 16),
    )
    .join(' ');
}

function variables(
  colors: (typeof brandConfig.colors)[keyof typeof brandConfig.colors],
  indent: string,
) {
  return (Object.entries(cssNames) as [BrandColorToken, string][])
    .map(
      ([token, cssName]) =>
        `${indent}--${cssName}: ${hexToRgbTriplet(colors[token])};`,
    )
    .join('\n');
}

const colorMappings = Object.values(cssNames)
  .map((name) => `  --color-${name}: rgb(var(--${name}));`)
  .join('\n');

const generated = `/* AUTO-GENERATED by scripts/generate-theme.ts. Do not edit directly. */
@import 'tailwindcss/theme.css' layer(theme);
@import 'tailwindcss/preflight.css' layer(base);
@import 'tailwindcss/utilities.css';
@import 'nativewind/theme';
@source './';

@layer theme {
  :root {
${variables(brandConfig.colors.light, '    ')}
  }

  @media (prefers-color-scheme: dark) {
    :root {
${variables(brandConfig.colors.dark, '      ')}
    }
  }

  :root.dark {
${variables(brandConfig.colors.dark, '    ')}
  }

  :root.light {
${variables(brandConfig.colors.light, '    ')}
  }
}

@theme inline {
  --font-sans: ${brandConfig.typography.sans};
${colorMappings}
}
`;

async function main() {
  const checkOnly = process.argv.includes('--check');

  if (checkOnly) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');

    if (current !== generated) {
      throw new Error(
        'src/global.css is out of date. Run `pnpm theme:sync`.',
      );
    }

    console.log('Generated theme CSS is up to date.');
    return;
  }

  await writeFile(outputPath, generated);
  console.log('Generated src/global.css from brand-config.ts.');
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
